### ISSUE TITLE
iOS browsers only playing previews

### ISSUE THREAD

**Issue by gianpietro1** [ctjlewis/react-spotify-embed#3]
Hi, I've been testing the component in different devices, and found out that in iOS browsers, the player only plays "previews", even though I'm simultaneously using the web API with premium authentication. In a PC, player works normally.
Is there a way to pass a token to the embedded player or something like that?
Thanks.

**Comment by ctjlewis** [comment]
This just renders the preview embed that Spotify publishes. It's not a full player or anything, I think there's another library that offers that.

This one is meant to be as simple as possible, just paste the link, no auth or anything.

**Comment by gianpietro1** [comment]
> This just renders the preview embed that Spotify publishes. It's not a full player or anything, I think there's another library that offers that.
> 
> This one is meant to be as simple as possible, just paste the link, no auth or anything.

I see, thanks for your quick answer!
Side comment: I've been testing a full player library called `react-spotify-web-playback`, but it carries the limitations of the SDK, in which the audio stops when the track changes in background on iOS browsers, so it seems there's no workaround for iOS browsers :(
