### ISSUE TITLE
Unable to change color of iframe wrapper's background

### ISSUE THREAD

**Issue by AndrewNow** [ctjlewis/react-spotify-embed#5]
Hi all, thanks for the package.

I'm finding myself unable to style the background of the iframe that wraps the Spotify <html> tag. This causes an ugly white/transparent space that I can't seem to get rid of:

![image](https://github.com/ctjlewis/react-spotify-embed/assets/57265008/363ad608-b803-46e1-b23b-252a3d3150dd)

Notice here that I've unset the value of background (and have tried the same for background-color): 

![image](https://github.com/ctjlewis/react-spotify-embed/assets/57265008/b76402d5-50d5-453c-b031-55fdbd96eca8)

Typically with an iframe you'd be able to add a prop like allowTransparency="true" or assign a background color value, but I'm not seeing how I could do that in my case.

Here's my code:

```js
<SpotifyWrapper>
   <Spotify
     wide
     height="300px"
     link={balado?.embed}
   />
</SpotifyWrapper>
```

```js

const SpotifyWrapper = styled.div`
  height: 300px;
  position: relative;
  display: block;
  iframe {
    background: unset!important;
  }
`;
```

The closest solution I've found until now was to set the height of the player to 232px (which seems to be the tallest it'll go for some reason..?) and add a border-radius, but you can still see the white background near the corners:

![image](https://github.com/ctjlewis/react-spotify-embed/assets/57265008/49e1ce0e-c6ba-4a08-8fde-5d088c67dca5)

Thanks for your help!

**Comment by ctjlewis** [comment]
SpotifyWrapper is likely causing this. Just drop `<Spotify />` into the page directly. See the demo.

**Comment by AndrewNow** [comment]
The SpotifyWrapper div is not causing it, as when removed the issue persists. The issue is due to the iframe, which is within <Spotify />.

**Comment by AndrewNow** [comment]
> SpotifyWrapper is likely causing this. Just drop `<Spotify />` into the page directly. See the demo.

The SpotifyWrapper div is not causing it, as when removed the issue persists. The issue is due to the iframe, which is within `<Spotify />`.
