### ISSUE TITLE
not working when /intl-es/ is inside the url

### ISSUE THREAD

**Issue by cascharly** [ctjlewis/react-spotify-embed#6]
Context: using spotify app or web from Buenos Aires / Argentina.
Browser locale: es  // spanish

The url copied from Spotify contains an additional segment : **/intl-es/** before the track info.
https://open.spotify.com/intl-es/track/5pcG9pIhfDfCoPCeChSuSu?si=b4a2284e5c814e78

This make the component to not work.
Removing manualy  /intl-es/ works again.

I wil try to make a push fix when i have a chance.
I am solving it in my code by removing it with a regular expression.
` url.pathname = url.pathname.replace(/\/intl-\w+\//, "/");`
  
  Great work !!

**Comment by molul** [comment]
Same here. Currently workarounding this by removing that string from the url before passing it to the component.
